// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Pokemon struct {
	ID          uuid.UUID
	PokemonName string
	CaughtAt    time.Time
	JsonData    pqtype.NullRawMessage
}
